# Generated by Django 5.0.2 on 2024-04-30 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
